// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MooveTeqBooking.Data;

namespace MooveTeqBooking.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210607094432_BogusDataWithNewHash")]
    partial class BogusDataWithNewHash
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15");

            modelBuilder.Entity("MooveTeqBooking.Data.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalTripCost")
                        .HasColumnType("REAL");

                    b.Property<int?>("TripDiscountPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TripDistance")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MooveTeqBooking.Data.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            FirstName = "Demo",
                            IsAdmin = true,
                            LastName = "Admin",
                            PasswordHash = "s3avW9Ui/GGhyw9H/5hS1uNvgMKYCO0p:3e7fotqzOUEwq7Xyo1GP3/yE1hFGoS9Wc8QzpRYt/OxrHT+syDH2eXNWKGsTnHbk8O2Ml6ERk9pP+UNGLOt38A==",
                            UserName = "admin"
                        },
                        new
                        {
                            CustomerId = 2,
                            FirstName = "Debbie",
                            IsAdmin = false,
                            LastName = "Gusikowski",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Debbie_Gusikowski74"
                        },
                        new
                        {
                            CustomerId = 3,
                            FirstName = "Felicia",
                            IsAdmin = false,
                            LastName = "Koch",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Felicia40"
                        },
                        new
                        {
                            CustomerId = 4,
                            FirstName = "Frederick",
                            IsAdmin = false,
                            LastName = "Anderson",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Frederick73"
                        },
                        new
                        {
                            CustomerId = 5,
                            FirstName = "Bobbie",
                            IsAdmin = false,
                            LastName = "D'Amore",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Bobbie_DAmore"
                        },
                        new
                        {
                            CustomerId = 6,
                            FirstName = "Clark",
                            IsAdmin = false,
                            LastName = "Kulas",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Clark15"
                        },
                        new
                        {
                            CustomerId = 7,
                            FirstName = "Jodi",
                            IsAdmin = false,
                            LastName = "Moore",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Jodi.Moore17"
                        },
                        new
                        {
                            CustomerId = 8,
                            FirstName = "Clifton",
                            IsAdmin = false,
                            LastName = "Wisoky",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Clifton.Wisoky"
                        },
                        new
                        {
                            CustomerId = 9,
                            FirstName = "Ethel",
                            IsAdmin = false,
                            LastName = "Mitchell",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Ethel46"
                        },
                        new
                        {
                            CustomerId = 10,
                            FirstName = "Sheila",
                            IsAdmin = false,
                            LastName = "Glover",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Sheila30"
                        },
                        new
                        {
                            CustomerId = 11,
                            FirstName = "Lorraine",
                            IsAdmin = false,
                            LastName = "Renner",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Lorraine90"
                        },
                        new
                        {
                            CustomerId = 12,
                            FirstName = "Jenna",
                            IsAdmin = false,
                            LastName = "Dietrich",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Jenna_Dietrich"
                        },
                        new
                        {
                            CustomerId = 13,
                            FirstName = "Juan",
                            IsAdmin = false,
                            LastName = "Graham",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Juan.Graham33"
                        },
                        new
                        {
                            CustomerId = 14,
                            FirstName = "Ada",
                            IsAdmin = false,
                            LastName = "Armstrong",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Ada.Armstrong"
                        },
                        new
                        {
                            CustomerId = 15,
                            FirstName = "Rochelle",
                            IsAdmin = false,
                            LastName = "Gerlach",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Rochelle_Gerlach12"
                        },
                        new
                        {
                            CustomerId = 16,
                            FirstName = "Adam",
                            IsAdmin = false,
                            LastName = "Hoeger",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Adam.Hoeger23"
                        },
                        new
                        {
                            CustomerId = 17,
                            FirstName = "Hannah",
                            IsAdmin = false,
                            LastName = "Hayes",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Hannah.Hayes11"
                        },
                        new
                        {
                            CustomerId = 18,
                            FirstName = "Hector",
                            IsAdmin = false,
                            LastName = "Feest",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Hector75"
                        },
                        new
                        {
                            CustomerId = 19,
                            FirstName = "Ernesto",
                            IsAdmin = false,
                            LastName = "Bailey",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Ernesto.Bailey"
                        },
                        new
                        {
                            CustomerId = 20,
                            FirstName = "Anita",
                            IsAdmin = false,
                            LastName = "Bernier",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Anita38"
                        },
                        new
                        {
                            CustomerId = 21,
                            FirstName = "Ollie",
                            IsAdmin = false,
                            LastName = "Pollich",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Ollie_Pollich86"
                        },
                        new
                        {
                            CustomerId = 22,
                            FirstName = "Melvin",
                            IsAdmin = false,
                            LastName = "Legros",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Melvin.Legros"
                        },
                        new
                        {
                            CustomerId = 23,
                            FirstName = "Cesar",
                            IsAdmin = false,
                            LastName = "Crist",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Cesar10"
                        },
                        new
                        {
                            CustomerId = 24,
                            FirstName = "Vicky",
                            IsAdmin = false,
                            LastName = "Hoppe",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Vicky_Hoppe"
                        },
                        new
                        {
                            CustomerId = 25,
                            FirstName = "Caroline",
                            IsAdmin = false,
                            LastName = "Hermann",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Caroline_Hermann"
                        },
                        new
                        {
                            CustomerId = 26,
                            FirstName = "Ron",
                            IsAdmin = false,
                            LastName = "Crona",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Ron_Crona"
                        },
                        new
                        {
                            CustomerId = 27,
                            FirstName = "Lena",
                            IsAdmin = false,
                            LastName = "Trantow",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Lena_Trantow43"
                        },
                        new
                        {
                            CustomerId = 28,
                            FirstName = "Joanne",
                            IsAdmin = false,
                            LastName = "Metz",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Joanne.Metz"
                        },
                        new
                        {
                            CustomerId = 29,
                            FirstName = "Javier",
                            IsAdmin = false,
                            LastName = "Rowe",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Javier_Rowe"
                        },
                        new
                        {
                            CustomerId = 30,
                            FirstName = "Miriam",
                            IsAdmin = false,
                            LastName = "Kuhlman",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Miriam.Kuhlman38"
                        },
                        new
                        {
                            CustomerId = 31,
                            FirstName = "Allan",
                            IsAdmin = false,
                            LastName = "Spinka",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Allan.Spinka"
                        },
                        new
                        {
                            CustomerId = 32,
                            FirstName = "Dana",
                            IsAdmin = false,
                            LastName = "Reichel",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Dana_Reichel"
                        },
                        new
                        {
                            CustomerId = 33,
                            FirstName = "Guadalupe",
                            IsAdmin = false,
                            LastName = "Mosciski",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Guadalupe55"
                        },
                        new
                        {
                            CustomerId = 34,
                            FirstName = "Pat",
                            IsAdmin = false,
                            LastName = "Powlowski",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Pat34"
                        },
                        new
                        {
                            CustomerId = 35,
                            FirstName = "Marcia",
                            IsAdmin = false,
                            LastName = "Lueilwitz",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Marcia_Lueilwitz43"
                        },
                        new
                        {
                            CustomerId = 36,
                            FirstName = "Viola",
                            IsAdmin = false,
                            LastName = "Bosco",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Viola_Bosco90"
                        },
                        new
                        {
                            CustomerId = 37,
                            FirstName = "Beatrice",
                            IsAdmin = false,
                            LastName = "Predovic",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Beatrice_Predovic23"
                        },
                        new
                        {
                            CustomerId = 38,
                            FirstName = "Cecil",
                            IsAdmin = false,
                            LastName = "Shanahan",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Cecil22"
                        },
                        new
                        {
                            CustomerId = 39,
                            FirstName = "Alyssa",
                            IsAdmin = false,
                            LastName = "Bruen",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Alyssa61"
                        },
                        new
                        {
                            CustomerId = 40,
                            FirstName = "Marcella",
                            IsAdmin = false,
                            LastName = "Leuschke",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Marcella_Leuschke"
                        },
                        new
                        {
                            CustomerId = 41,
                            FirstName = "Julius",
                            IsAdmin = false,
                            LastName = "Wunsch",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Julius_Wunsch47"
                        },
                        new
                        {
                            CustomerId = 42,
                            FirstName = "Enrique",
                            IsAdmin = false,
                            LastName = "Barton",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Enrique54"
                        },
                        new
                        {
                            CustomerId = 43,
                            FirstName = "Gerardo",
                            IsAdmin = false,
                            LastName = "Blick",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Gerardo_Blick"
                        },
                        new
                        {
                            CustomerId = 44,
                            FirstName = "Stacy",
                            IsAdmin = false,
                            LastName = "Kilback",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Stacy52"
                        },
                        new
                        {
                            CustomerId = 45,
                            FirstName = "Tara",
                            IsAdmin = false,
                            LastName = "Towne",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Tara.Towne92"
                        },
                        new
                        {
                            CustomerId = 46,
                            FirstName = "Duane",
                            IsAdmin = false,
                            LastName = "O'Kon",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Duane.OKon57"
                        },
                        new
                        {
                            CustomerId = 47,
                            FirstName = "Ruben",
                            IsAdmin = false,
                            LastName = "Stiedemann",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Ruben_Stiedemann43"
                        },
                        new
                        {
                            CustomerId = 48,
                            FirstName = "Angel",
                            IsAdmin = false,
                            LastName = "Wiza",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Angel94"
                        },
                        new
                        {
                            CustomerId = 49,
                            FirstName = "Lillian",
                            IsAdmin = false,
                            LastName = "Jakubowski",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Lillian_Jakubowski"
                        },
                        new
                        {
                            CustomerId = 50,
                            FirstName = "Betsy",
                            IsAdmin = false,
                            LastName = "Haley",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Betsy12"
                        },
                        new
                        {
                            CustomerId = 51,
                            FirstName = "Erma",
                            IsAdmin = false,
                            LastName = "Will",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Erma_Will"
                        },
                        new
                        {
                            CustomerId = 52,
                            FirstName = "Sean",
                            IsAdmin = false,
                            LastName = "Gislason",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Sean_Gislason"
                        },
                        new
                        {
                            CustomerId = 53,
                            FirstName = "Angela",
                            IsAdmin = false,
                            LastName = "Welch",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Angela.Welch"
                        },
                        new
                        {
                            CustomerId = 54,
                            FirstName = "April",
                            IsAdmin = false,
                            LastName = "Kuphal",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "April47"
                        },
                        new
                        {
                            CustomerId = 55,
                            FirstName = "Kelly",
                            IsAdmin = false,
                            LastName = "Emard",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Kelly.Emard"
                        },
                        new
                        {
                            CustomerId = 56,
                            FirstName = "Frankie",
                            IsAdmin = false,
                            LastName = "Gibson",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Frankie87"
                        },
                        new
                        {
                            CustomerId = 57,
                            FirstName = "Essie",
                            IsAdmin = false,
                            LastName = "Green",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Essie91"
                        },
                        new
                        {
                            CustomerId = 58,
                            FirstName = "Gerard",
                            IsAdmin = false,
                            LastName = "Stoltenberg",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Gerard_Stoltenberg19"
                        },
                        new
                        {
                            CustomerId = 59,
                            FirstName = "Deanna",
                            IsAdmin = false,
                            LastName = "Ullrich",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Deanna.Ullrich96"
                        },
                        new
                        {
                            CustomerId = 60,
                            FirstName = "Sammy",
                            IsAdmin = false,
                            LastName = "Reinger",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Sammy.Reinger50"
                        },
                        new
                        {
                            CustomerId = 61,
                            FirstName = "Josephine",
                            IsAdmin = false,
                            LastName = "Bednar",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Josephine.Bednar40"
                        },
                        new
                        {
                            CustomerId = 62,
                            FirstName = "Pauline",
                            IsAdmin = false,
                            LastName = "Adams",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Pauline.Adams"
                        },
                        new
                        {
                            CustomerId = 63,
                            FirstName = "Marian",
                            IsAdmin = false,
                            LastName = "Johns",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Marian47"
                        },
                        new
                        {
                            CustomerId = 64,
                            FirstName = "Patricia",
                            IsAdmin = false,
                            LastName = "Lueilwitz",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Patricia97"
                        },
                        new
                        {
                            CustomerId = 65,
                            FirstName = "Meredith",
                            IsAdmin = false,
                            LastName = "Volkman",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Meredith59"
                        },
                        new
                        {
                            CustomerId = 66,
                            FirstName = "Tyrone",
                            IsAdmin = false,
                            LastName = "Gottlieb",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Tyrone_Gottlieb"
                        },
                        new
                        {
                            CustomerId = 67,
                            FirstName = "Brandon",
                            IsAdmin = false,
                            LastName = "Emmerich",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Brandon_Emmerich"
                        },
                        new
                        {
                            CustomerId = 68,
                            FirstName = "Ray",
                            IsAdmin = false,
                            LastName = "Glover",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Ray21"
                        },
                        new
                        {
                            CustomerId = 69,
                            FirstName = "Jake",
                            IsAdmin = false,
                            LastName = "Walter",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Jake_Walter63"
                        },
                        new
                        {
                            CustomerId = 70,
                            FirstName = "Sandra",
                            IsAdmin = false,
                            LastName = "Koch",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Sandra_Koch"
                        },
                        new
                        {
                            CustomerId = 71,
                            FirstName = "Monica",
                            IsAdmin = false,
                            LastName = "Abbott",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Monica.Abbott12"
                        },
                        new
                        {
                            CustomerId = 72,
                            FirstName = "Dexter",
                            IsAdmin = false,
                            LastName = "Gislason",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Dexter86"
                        },
                        new
                        {
                            CustomerId = 73,
                            FirstName = "Bethany",
                            IsAdmin = false,
                            LastName = "Ferry",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Bethany.Ferry"
                        },
                        new
                        {
                            CustomerId = 74,
                            FirstName = "Melba",
                            IsAdmin = false,
                            LastName = "Schuster",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Melba95"
                        },
                        new
                        {
                            CustomerId = 75,
                            FirstName = "Cecelia",
                            IsAdmin = false,
                            LastName = "Reynolds",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Cecelia_Reynolds19"
                        },
                        new
                        {
                            CustomerId = 76,
                            FirstName = "Malcolm",
                            IsAdmin = false,
                            LastName = "Morissette",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Malcolm_Morissette"
                        },
                        new
                        {
                            CustomerId = 77,
                            FirstName = "Ellis",
                            IsAdmin = false,
                            LastName = "Schneider",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Ellis62"
                        },
                        new
                        {
                            CustomerId = 78,
                            FirstName = "Doug",
                            IsAdmin = false,
                            LastName = "Beer",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Doug50"
                        },
                        new
                        {
                            CustomerId = 79,
                            FirstName = "Abel",
                            IsAdmin = false,
                            LastName = "Abernathy",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Abel98"
                        },
                        new
                        {
                            CustomerId = 80,
                            FirstName = "Chelsea",
                            IsAdmin = false,
                            LastName = "Schamberger",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Chelsea.Schamberger28"
                        },
                        new
                        {
                            CustomerId = 81,
                            FirstName = "Benny",
                            IsAdmin = false,
                            LastName = "Powlowski",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Benny64"
                        },
                        new
                        {
                            CustomerId = 82,
                            FirstName = "Geoffrey",
                            IsAdmin = false,
                            LastName = "Boyer",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Geoffrey59"
                        },
                        new
                        {
                            CustomerId = 83,
                            FirstName = "Blanca",
                            IsAdmin = false,
                            LastName = "Toy",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Blanca_Toy"
                        },
                        new
                        {
                            CustomerId = 84,
                            FirstName = "Malcolm",
                            IsAdmin = false,
                            LastName = "Heathcote",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Malcolm79"
                        },
                        new
                        {
                            CustomerId = 85,
                            FirstName = "Juana",
                            IsAdmin = false,
                            LastName = "Cruickshank",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Juana.Cruickshank98"
                        },
                        new
                        {
                            CustomerId = 86,
                            FirstName = "Clay",
                            IsAdmin = false,
                            LastName = "Haley",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Clay_Haley9"
                        },
                        new
                        {
                            CustomerId = 87,
                            FirstName = "Laurence",
                            IsAdmin = false,
                            LastName = "Dicki",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Laurence92"
                        },
                        new
                        {
                            CustomerId = 88,
                            FirstName = "Jordan",
                            IsAdmin = false,
                            LastName = "Kulas",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Jordan93"
                        },
                        new
                        {
                            CustomerId = 89,
                            FirstName = "Timothy",
                            IsAdmin = false,
                            LastName = "McCullough",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Timothy.McCullough84"
                        },
                        new
                        {
                            CustomerId = 90,
                            FirstName = "Jacob",
                            IsAdmin = false,
                            LastName = "Runolfsson",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Jacob.Runolfsson"
                        },
                        new
                        {
                            CustomerId = 91,
                            FirstName = "Willie",
                            IsAdmin = false,
                            LastName = "Lueilwitz",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Willie25"
                        },
                        new
                        {
                            CustomerId = 92,
                            FirstName = "Loren",
                            IsAdmin = false,
                            LastName = "Schaden",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Loren_Schaden34"
                        },
                        new
                        {
                            CustomerId = 93,
                            FirstName = "Beulah",
                            IsAdmin = false,
                            LastName = "Waelchi",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Beulah_Waelchi"
                        },
                        new
                        {
                            CustomerId = 94,
                            FirstName = "Nicolas",
                            IsAdmin = false,
                            LastName = "Von",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Nicolas_Von54"
                        },
                        new
                        {
                            CustomerId = 95,
                            FirstName = "Sonya",
                            IsAdmin = false,
                            LastName = "Murray",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Sonya.Murray21"
                        },
                        new
                        {
                            CustomerId = 96,
                            FirstName = "Brad",
                            IsAdmin = false,
                            LastName = "Senger",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Brad65"
                        },
                        new
                        {
                            CustomerId = 97,
                            FirstName = "Brandon",
                            IsAdmin = false,
                            LastName = "Kutch",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Brandon_Kutch"
                        },
                        new
                        {
                            CustomerId = 98,
                            FirstName = "Sherri",
                            IsAdmin = false,
                            LastName = "Corwin",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Sherri96"
                        },
                        new
                        {
                            CustomerId = 99,
                            FirstName = "Arturo",
                            IsAdmin = false,
                            LastName = "Weissnat",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Arturo_Weissnat60"
                        },
                        new
                        {
                            CustomerId = 100,
                            FirstName = "Salvador",
                            IsAdmin = false,
                            LastName = "Roob",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Salvador_Roob81"
                        },
                        new
                        {
                            CustomerId = 101,
                            FirstName = "Ashley",
                            IsAdmin = false,
                            LastName = "Pollich",
                            PasswordHash = "ehEfflYUWfqO6mt6J2WrgmlCjIHViCkd:N5Tnz2m+GoVjcxewwZ2lxenoZNqrhjBC7lNyg46rUie26uAkpcZCRsBeEfC/ltNif8qIAnnj3pgosQn0zT7HXQ==",
                            UserName = "Ashley44"
                        });
                });

            modelBuilder.Entity("MooveTeqBooking.Data.Booking", b =>
                {
                    b.HasOne("MooveTeqBooking.Data.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
