// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MooveTeqBooking.Data;

namespace MooveTeqBooking.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210604101233_BogusDataWithPasswd")]
    partial class BogusDataWithPasswd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15");

            modelBuilder.Entity("MooveTeqBooking.Data.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalTripCost")
                        .HasColumnType("REAL");

                    b.Property<int?>("TripDiscountPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TripDistance")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MooveTeqBooking.Data.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            FirstName = "Demo",
                            IsAdmin = true,
                            LastName = "Admin",
                            PasswordHash = "cYnsvE5m+9OpbgOK69x76wozBJuYV5Jm:uccBM5nX041hFULOsL/1adJg+UmY5/Jy61iV1QP6xiWX6eTwuxGJ81Dlal8y0gtVYaXE26orCGU+gNxeKZbx1Q==",
                            UserName = "admin"
                        },
                        new
                        {
                            CustomerId = 2,
                            FirstName = "Melissa",
                            IsAdmin = false,
                            LastName = "Mitchell",
                            PasswordHash = "5POEoz+b8/2NjeqpcB+xVUSBvJdgTWiq:TIV5q2hxwC+SwJvIO6+3d+0I/uNZYpkGKmhNeuPDeZTMbv0fENNFVKwdUCkmUQC81pnOCj9Rh9I/IER3bX8DIw==",
                            UserName = "Melissa.Mitchell"
                        },
                        new
                        {
                            CustomerId = 3,
                            FirstName = "Andres",
                            IsAdmin = false,
                            LastName = "Padberg",
                            PasswordHash = "sSnLjIAw/Q7AEUuCRWP8Sn57MaZt/snt:46Pn6AMg04t1EJeV9IPYwvrrzlRxIO39WoWAeJS1rSCXaQMkplQpyby5OXfMZRnLesA2wjSuW9dWjzYtxJaiwA==",
                            UserName = "Andres_Padberg88"
                        },
                        new
                        {
                            CustomerId = 4,
                            FirstName = "Charlene",
                            IsAdmin = false,
                            LastName = "Pouros",
                            PasswordHash = "c/xdv9NcY1grVZYgyVEzarIpBwGjDDCg:p3+vt+2vHwiop7B2ySKuFDC27y6iMCRnj4YU0dWEGYhRHDdSAf7DwvR1haNnkRUJPj4jNoCWOyJCvFzppf/rUw==",
                            UserName = "Charlene19"
                        },
                        new
                        {
                            CustomerId = 5,
                            FirstName = "Charlotte",
                            IsAdmin = false,
                            LastName = "Predovic",
                            PasswordHash = "hjoDOknOrs72KSPVhcWQ+4IRzH5a14gr:EdF7s2i+vuGj03roe3LPFWn+dYaxJiOSaecdfpfiu6plbbI6uLqqSSPTprSm8M6HLklTbWXT3J8a5si2SNutvA==",
                            UserName = "Charlotte70"
                        },
                        new
                        {
                            CustomerId = 6,
                            FirstName = "Gladys",
                            IsAdmin = false,
                            LastName = "Kreiger",
                            PasswordHash = "tGKXRJgpYNeZfF7oWTQwTcLyokXONqvg:DHNdF+FfYkt6W5H+SQCHFb7h39eCNDweWMalcKdzzlLshLk+O27vYI8LZsPp+L31SwFzc4npvjoSNe4tAikPgA==",
                            UserName = "Gladys.Kreiger95"
                        },
                        new
                        {
                            CustomerId = 7,
                            FirstName = "Kristen",
                            IsAdmin = false,
                            LastName = "Grady",
                            PasswordHash = "WPpqWTTDEccNrMPzNGK2ihWaXCdC/CcQ:SwViP+IHw88hiqmEQIn8DR4XzAp1Oa19DEJ+CPelh5HqxXATo9bGI5e2LHUd4BMJrN9ZPOTuuqHZnlVppkWksQ==",
                            UserName = "Kristen.Grady23"
                        },
                        new
                        {
                            CustomerId = 8,
                            FirstName = "Victoria",
                            IsAdmin = false,
                            LastName = "Walker",
                            PasswordHash = "2JPITmk0PXBWWMrxLIocXzGfi/FRRUZk:YNAzxgwOMkl9u4Re+UbgpO4nrAkeXOGnj5juT1OUgnbyh6PoRKLZYYUhhzReLbcFv1R9uCNZ9poXKxdUJPcfXg==",
                            UserName = "Victoria_Walker43"
                        },
                        new
                        {
                            CustomerId = 9,
                            FirstName = "Dewey",
                            IsAdmin = false,
                            LastName = "Auer",
                            PasswordHash = "wWIK3VJnhxUsEAIVS9Q8qIm5bQV1Kz8W:PaTz+TkkrAuADtWQwDJtCEcruZ3PF2gWfr1jaUXx81Lxx0EwHpgc13DKaLoQ8BKm6pizxEnPmpYRWVBJswb+mg==",
                            UserName = "Dewey78"
                        },
                        new
                        {
                            CustomerId = 10,
                            FirstName = "Caroline",
                            IsAdmin = false,
                            LastName = "Dooley",
                            PasswordHash = "k1DiEX99RUrSnvcQI3OWPh69aKzE30qh:WRUJgiLw0ioE1HsLGUhAykAqXrpVcLSzl+QEF3it+UUeBml3hTUXoCx3bAedmeJtHQPZ36A893IAcO7ae57cpQ==",
                            UserName = "Caroline_Dooley33"
                        },
                        new
                        {
                            CustomerId = 11,
                            FirstName = "Benjamin",
                            IsAdmin = false,
                            LastName = "Koelpin",
                            PasswordHash = "MDiNUcMN5VyFvhYR2tFsXzU1THQ7SeHg:wopFXkSa/ubWdl15voWfhusA9nQfIWLG6gblyy2W5DnLv4+Qx5QtnpbIJmmKmSXoNbw9tM9VuhoMpZZMlySO0w==",
                            UserName = "Benjamin.Koelpin41"
                        },
                        new
                        {
                            CustomerId = 12,
                            FirstName = "Emily",
                            IsAdmin = false,
                            LastName = "Little",
                            PasswordHash = "jHbsaAhxWhoCq3kQDXtHB0u/iBdAK9H0:bmpXiiXiTOLGlLZ5GIkUruGEnHcZhqHbpDdeb8XlWhiU2oYtY03xx/14rtf+8NxGEOAxFSS4BpejRabMuxgyOw==",
                            UserName = "Emily_Little49"
                        },
                        new
                        {
                            CustomerId = 13,
                            FirstName = "Lonnie",
                            IsAdmin = false,
                            LastName = "Adams",
                            PasswordHash = "NG8PgvMIPAu3ferhTqtcglAcajx15bMC:nGV5bW7xmdHZipmGqYww3bpPo/3pOzyxYyfj40tkHLEYmTrYOXQKEyeknkMBDQ/jx74TBONlXwWcXWE0O+MjXA==",
                            UserName = "Lonnie_Adams84"
                        },
                        new
                        {
                            CustomerId = 14,
                            FirstName = "Jackie",
                            IsAdmin = false,
                            LastName = "Keebler",
                            PasswordHash = "+m3ckRU7HRPED0npSxKRRbzB/B/dIMSE:BLG3sGGCr1MiIcwNfLKDPvqx/h8jxSKpjcif5sHHLLRD9EjIsEfMvpOkWqoXBCNRDptc49AFdFTuv3JVJqfpdA==",
                            UserName = "Jackie_Keebler49"
                        },
                        new
                        {
                            CustomerId = 15,
                            FirstName = "Forrest",
                            IsAdmin = false,
                            LastName = "O'Connell",
                            PasswordHash = "XypzAohUmGgG7NmoLm2pQM3jWlxVPD+9:ZHlNhdy9lpe0N8MHfW89y65ZqxEhOin8tFQmic4HoLz+eX2ekW57ruQSlE2ggV/kfLNmNUzYutVVpMAWJWCOTA==",
                            UserName = "Forrest.OConnell"
                        },
                        new
                        {
                            CustomerId = 16,
                            FirstName = "Ann",
                            IsAdmin = false,
                            LastName = "Crist",
                            PasswordHash = "8HGIQuzblhsrtUuw5zNOXjUuQC1D6+NK:WP+sM48KY6SWZ0yQTsWQ1v7b99SL3+yB+dImbyNtc5u2btERuPEGTYXH4C/0lmAjxN9D4ae7ZNJQK59wi2cCSw==",
                            UserName = "Ann_Crist"
                        },
                        new
                        {
                            CustomerId = 17,
                            FirstName = "Kristen",
                            IsAdmin = false,
                            LastName = "Corkery",
                            PasswordHash = "NG944Dn1FygpKLlQKd4t9ynX2U3TQmeW:h29IDxkfxT9eeuRV0kOVN5QO0MJLh1vOIxMe7gBH1opsa7zDvmEivdzMzvncIhH0F073cqzYrO+RccLG/d2T3Q==",
                            UserName = "Kristen_Corkery"
                        },
                        new
                        {
                            CustomerId = 18,
                            FirstName = "Carmen",
                            IsAdmin = false,
                            LastName = "Kuhlman",
                            PasswordHash = "9qdCPtrq0Azdp/145uRhBVfzeKfk2SJB:OMeHK11T028rclnpiI82+IjvbtvHtIW6c0ri2EMdcrRsE4AKhF3O3Hri5xp+E7ug7MGFKolWPWfL5GZh2yZ14w==",
                            UserName = "Carmen45"
                        },
                        new
                        {
                            CustomerId = 19,
                            FirstName = "Timmy",
                            IsAdmin = false,
                            LastName = "Sauer",
                            PasswordHash = "u4r90XxYqI7pLeoV2CV+PvTRzusjJOBq:WtfzrnhMwAFnbx6W67FBRSPf0xRpT9CcgHrAeChOGzN63kQioLAXyq7wXGG7OvgFnYrgJaylBph7lzLTxyqu4A==",
                            UserName = "Timmy_Sauer"
                        },
                        new
                        {
                            CustomerId = 20,
                            FirstName = "Clara",
                            IsAdmin = false,
                            LastName = "Conn",
                            PasswordHash = "G7AN04CODyY92K6+oqfoYwgRnyLnhjZ1:09eh3FbN2e0pj1Uw2OWqW1db+S8QGN6pLDusiyrNhXzTds5/FckbX+OEa36x7GzQsH66MbC56fSE3sFxjrNL3g==",
                            UserName = "Clara.Conn79"
                        },
                        new
                        {
                            CustomerId = 21,
                            FirstName = "Sean",
                            IsAdmin = false,
                            LastName = "Feil",
                            PasswordHash = "23eattgZjWdyUFIi6vtDSmdKsWpWoo9b:xWjmksO5jAh42pLFJwzWs73kjqXaO4mo8Z2dbyNYOzFE99bZLA/Ix+LMn2blwIZGXgNSvYrwsNDWYv582Ayblg==",
                            UserName = "Sean_Feil"
                        },
                        new
                        {
                            CustomerId = 22,
                            FirstName = "Kellie",
                            IsAdmin = false,
                            LastName = "Murray",
                            PasswordHash = "Ln3XFE+qMoDRmJfqHtPwCO3C+dIBobmW:lUcM0r5X25mjCPn/DnxGzUgxpsVyQ+ffKrRZBf1NirRh89jatBOHySJ1H1tQ0pgSZT3QxQjzl5MN2HrtfCllZA==",
                            UserName = "Kellie.Murray"
                        },
                        new
                        {
                            CustomerId = 23,
                            FirstName = "Dale",
                            IsAdmin = false,
                            LastName = "Tromp",
                            PasswordHash = "M+iSSBAHeO9ByPW8pOyYsaOR93PMeKCk:hmSxMyuerQ9AGET/z+eX3tqUsSHddl2F8MAQ4mnWXsGon/QIvWztmW9vIP9eYyXPmnA7pPyVCm7GvkowASy2Bw==",
                            UserName = "Dale24"
                        },
                        new
                        {
                            CustomerId = 24,
                            FirstName = "Caleb",
                            IsAdmin = false,
                            LastName = "Hintz",
                            PasswordHash = "h8mjSWNNDdzGraSXlYoYpwU3LNoUW2dE:flDoWEDwC1RYew1GKNDqXvCnJu3ovQIyh4wuF8n4UMzvZMV2rxIOfnVrOOeuXOA2sFSaEnWdKIJrzwLJQZ6mQQ==",
                            UserName = "Caleb.Hintz"
                        },
                        new
                        {
                            CustomerId = 25,
                            FirstName = "Eduardo",
                            IsAdmin = false,
                            LastName = "Huel",
                            PasswordHash = "/4pxDfrNnWdUomEJDRJyWdnbD1RhxuSR:Vn0naQ5xPopoyzuM1aLIEtNGLbln5afsXxJlUJLZvwbp79hJ562VWGPxR+54ikwCQKpRhPSs16pOOJo69b9Mhg==",
                            UserName = "Eduardo.Huel87"
                        },
                        new
                        {
                            CustomerId = 26,
                            FirstName = "Cody",
                            IsAdmin = false,
                            LastName = "Kuhic",
                            PasswordHash = "9akjwq8tVCVSGbWJVSPVB4TKMlFoIoAq:YRzDPD++pNkhT+XF53VJ03XW94o+VLN1W9Xgzm+NOBHUR4gmpLdux/DxJj3jeEsJavg6pM4yHSePQv4PbCXkrw==",
                            UserName = "Cody85"
                        },
                        new
                        {
                            CustomerId = 27,
                            FirstName = "Dominick",
                            IsAdmin = false,
                            LastName = "Lesch",
                            PasswordHash = "kiQ27BjoNss2GGLiiKn90inqmgygQCe2:3kP59M3CVqo/zNTt2//wqNTkqAE2OjP4oHCBJ1/qcREECnDZx3omIFtO60wslPXj23AfGWP1k6FuzpXR8Kn9UA==",
                            UserName = "Dominick_Lesch92"
                        },
                        new
                        {
                            CustomerId = 28,
                            FirstName = "Elizabeth",
                            IsAdmin = false,
                            LastName = "Nikolaus",
                            PasswordHash = "aP/87gaKWGDOtfcmC+nlV4EFq93Mxw9Q:5TW+v13tUK4fNr8o54/KKcH1V+jXcJ3pamsnTrXrx0LOdLhaxJPQ2ionUxcPnKy7kX97GLX+76+yBUlJB45/Og==",
                            UserName = "Elizabeth_Nikolaus"
                        },
                        new
                        {
                            CustomerId = 29,
                            FirstName = "Mamie",
                            IsAdmin = false,
                            LastName = "Spencer",
                            PasswordHash = "PXEtyi/nbYvQIOtqUOKK3z460mwthb2+:UdRnZIKlUC8HkAD0kZ7iEOXrQ215vOEh2Mai+4mi2edCGQh1wbUe4i5FyVSrZtpLXG3z6okXLsYeZ9sLankw+w==",
                            UserName = "Mamie.Spencer"
                        },
                        new
                        {
                            CustomerId = 30,
                            FirstName = "Terry",
                            IsAdmin = false,
                            LastName = "Fadel",
                            PasswordHash = "CYtTUXrcDaJqKw5iac71pZMrR597XImC:vS2O1/dkUroWRtFtAX4SRew70ewttSRFO+x3ket+H72PwoJuzAGpOyODG9r8yG5piDWLhiD35qlsjKOelOH72w==",
                            UserName = "Terry.Fadel"
                        },
                        new
                        {
                            CustomerId = 31,
                            FirstName = "Willie",
                            IsAdmin = false,
                            LastName = "Walsh",
                            PasswordHash = "rLePcu/3OGiRkpKCQ/8LPIMZTVRRx/P8:Ke5JwNMDHC6cCGzXonEbRZleBbJkD8PrGOM/MfeL+l0Llf1eS5MKRZxvvIoMFzb9VY6GV+W4Fksvzzmj0PUJmg==",
                            UserName = "Willie.Walsh"
                        },
                        new
                        {
                            CustomerId = 32,
                            FirstName = "Dianne",
                            IsAdmin = false,
                            LastName = "Bruen",
                            PasswordHash = "GfQqI6oI36pbQcSf5OkhN0cuLDrjZp6X:vL0/dKhSptV8hEyRFXfzxkki80ZlAgDHujSrIGFRh6YqgAHvf+C1d5oZal0+A8I4Qe4m44FsjGTZ4RLyBMgijA==",
                            UserName = "Dianne.Bruen78"
                        },
                        new
                        {
                            CustomerId = 33,
                            FirstName = "Kristie",
                            IsAdmin = false,
                            LastName = "Bergstrom",
                            PasswordHash = "3W/SniWssunpxbmXfU1ztn6Z3X924yvN:4HQuQVSMDP0IhlqS432a4qHGwUpuj5ost0XGQXbIPR73gtj0T/yD/kfNOT6KFIGCr4sWHgXGskrncxP1sxlM2g==",
                            UserName = "Kristie71"
                        },
                        new
                        {
                            CustomerId = 34,
                            FirstName = "Cedric",
                            IsAdmin = false,
                            LastName = "Brown",
                            PasswordHash = "w1cHYe5JKEnHzYwRko8PYDHMozG6PG3p:PD+0XVu1lApiXpzzo4qVcHn2yJBDxy6YY8y0mklY8fX0zKxQ8xJBSivmdJWjEc5Hsu2MeLo9VVHB87meLjRmaA==",
                            UserName = "Cedric.Brown16"
                        },
                        new
                        {
                            CustomerId = 35,
                            FirstName = "Scott",
                            IsAdmin = false,
                            LastName = "Jakubowski",
                            PasswordHash = "jeSrjdNybbRNQ37iQlVDsFZZYYO5/wNT:ETqoxHodYQ13JQUkhlhZT9OwCceWaSmVfumXuHExcfRrVVGhhnP9B8jD2GUc4RbJgwPpgdcQiXkcgbxlPamXpg==",
                            UserName = "Scott_Jakubowski"
                        },
                        new
                        {
                            CustomerId = 36,
                            FirstName = "Marty",
                            IsAdmin = false,
                            LastName = "Waelchi",
                            PasswordHash = "e20k1RQDdeq8zqlLj1bYZ+qBKRORzsLG:ZZLBEJTndWUiYi5QRkcIrydvj87VK0+mISoV3R0tLJW1gna7X1srUqRKiu/z5bT583elKSp20Y7/nTwtnzIQpA==",
                            UserName = "Marty_Waelchi19"
                        },
                        new
                        {
                            CustomerId = 37,
                            FirstName = "Sonya",
                            IsAdmin = false,
                            LastName = "Stark",
                            PasswordHash = "WJ34Iaz77YPe4Y75mOc6QhNYG9VhlLjt:qaEMV9DZptnXUPW04LP0Q78NUhL7OVTzbS3G8jU6+IWx83bw4Qb7qT95TJcoqdY3tqUiP6uKP/zlDYnZYwzTzA==",
                            UserName = "Sonya.Stark"
                        },
                        new
                        {
                            CustomerId = 38,
                            FirstName = "Laverne",
                            IsAdmin = false,
                            LastName = "Lang",
                            PasswordHash = "JeJeNH2S69W2IRctbO3lA+/kpEEdqyhf:pIPHcraD+18rNFQCDB39s9Y47PJWn+DTOj5Hp5/pY8xHgojp7VFZIFHsm9uQsz5fet+g0Z8pZxz2dgVjXWpVYg==",
                            UserName = "Laverne.Lang"
                        },
                        new
                        {
                            CustomerId = 39,
                            FirstName = "Freda",
                            IsAdmin = false,
                            LastName = "Schoen",
                            PasswordHash = "3t6FN16T2ZuTgcpfZ+KGup2YF13QrVwW:q6qZ8LbH3SHHF6J/fOHAvedqiCkqh0WksgwQygYNwGhGqhK/5eT/68iSdJTcyMoKha+pt2V13+kCvwlYhnf26Q==",
                            UserName = "Freda_Schoen"
                        },
                        new
                        {
                            CustomerId = 40,
                            FirstName = "Edmond",
                            IsAdmin = false,
                            LastName = "Kohler",
                            PasswordHash = "vbbnKHtc/GhA4HIT5o3/RzBxvUPH/xuT:jBqc9tb7Rilixp/c10dQQs9dci4n5PUeayUVqdX0d93ReRx1JrKTmMMBUmeAl5oOq6tAc1Fpwm4p17qZ8rVYEQ==",
                            UserName = "Edmond_Kohler47"
                        },
                        new
                        {
                            CustomerId = 41,
                            FirstName = "Jacqueline",
                            IsAdmin = false,
                            LastName = "Bailey",
                            PasswordHash = "XCjsryAG4CDU6XpyH5ImYV0FmejUuPbz:6NHGUiFVAU2E/jXscW+INWKAx9ng992/cb+bKhZY0lYUwqXq7G/7U4iQJzcQtEiJ4rFFI6TNPN9gjflJ5orWdA==",
                            UserName = "Jacqueline69"
                        },
                        new
                        {
                            CustomerId = 42,
                            FirstName = "Debbie",
                            IsAdmin = false,
                            LastName = "McLaughlin",
                            PasswordHash = "qKCC1hdJXJ7zGBCMzKkwUzTqbR+ZxbmM:D9cTfcXcnEkSxlCOWWckvqTt0bQ5hIE4qZq8Jb6MnrtYhl2kmKXutiNu/OLpkk/iTqo9vUkUq71Q+kPBrAmXxw==",
                            UserName = "Debbie.McLaughlin"
                        },
                        new
                        {
                            CustomerId = 43,
                            FirstName = "Calvin",
                            IsAdmin = false,
                            LastName = "Wisoky",
                            PasswordHash = "ai9Rq6MYfogtNFYKQZwVALywHDpePCFW:NUIQw265vY+FsNNAo3nksxaf7EiFDOXQvEf1+EfkE85D2Z+S+Z89azruTJwz64kJqyUAg/IafuOgsCEDb/QNUA==",
                            UserName = "Calvin.Wisoky"
                        },
                        new
                        {
                            CustomerId = 44,
                            FirstName = "Mandy",
                            IsAdmin = false,
                            LastName = "Schowalter",
                            PasswordHash = "8aeQ2RVGgmKCwkFjJdtseTz9n91k0oAS:OZqwayq4j87TYUShWCY1HcBb3AT+OhyT/DGtyowbXy4BMj31r91a/hAbcdknhY0eBZTw4hDfwhp7N4GfmAKkgA==",
                            UserName = "Mandy.Schowalter24"
                        },
                        new
                        {
                            CustomerId = 45,
                            FirstName = "Herman",
                            IsAdmin = false,
                            LastName = "Stokes",
                            PasswordHash = "Rld2u3Zfa0qnnKRsDNRkDwtIX/g0hFie:ivTcNu25TJeJnXJK86yVbpGD66bcfR4fuFHdsM1xDWiXa47TK1EfavRH1sxNKveQG+q4bX2XIiaulspKp6Y8lw==",
                            UserName = "Herman_Stokes71"
                        },
                        new
                        {
                            CustomerId = 46,
                            FirstName = "Rogelio",
                            IsAdmin = false,
                            LastName = "Rippin",
                            PasswordHash = "kYApdW/8x+u8Vomp3pMYGeBoaY+UOVt+:/bJEYNWBln1VUn6yEN6qbeX+okoPqjFT8arcbTHfK4JFEl8StwM7da1HGch6JOCNH9aIJ/sXIWJhHsY5z9Nm3Q==",
                            UserName = "Rogelio18"
                        },
                        new
                        {
                            CustomerId = 47,
                            FirstName = "Tommie",
                            IsAdmin = false,
                            LastName = "Hilpert",
                            PasswordHash = "UUYdrrO0R2YAZeIuWmY1Fe/CxHrTHVtb:R4JcQScE+wh9mRHyFnnxawgdXLfONNU/A8CEx5Eh7RyESucuZUw20DYJQDAfJgl8ozvwCPCvccpD+SSybAKsJQ==",
                            UserName = "Tommie.Hilpert2"
                        },
                        new
                        {
                            CustomerId = 48,
                            FirstName = "Timmy",
                            IsAdmin = false,
                            LastName = "Tillman",
                            PasswordHash = "HLyWcQGCuESFNvTlgT2RbFrFgRkXx+0S:HuaU76u7ilqSVKIyYSelLwjSRGYYZrEQX5syc9IuUp86A7wYfMiPLrqmc0lew40fDJiW3IC0HqEZN4p7aEW+4Q==",
                            UserName = "Timmy.Tillman8"
                        },
                        new
                        {
                            CustomerId = 49,
                            FirstName = "June",
                            IsAdmin = false,
                            LastName = "Wunsch",
                            PasswordHash = "3UcM8/QJ+qm7bpBdPOQy6SYKlXAWvV2G:3isCUabfOvn1w5HErhyeNXi728zgYeWwV+t28WpGCCMCVPtE/TDZyODyx3Sy4M8MKuGwCZC6LVZ6ynkyUnMbSw==",
                            UserName = "June_Wunsch"
                        },
                        new
                        {
                            CustomerId = 50,
                            FirstName = "Delbert",
                            IsAdmin = false,
                            LastName = "Bauch",
                            PasswordHash = "jIt48puiicHhPMwnHM8YXAwQ5tYBba0d:xDEyb7hypCdwnIveTvrN0YjmkHilii+t4qi4eJtxxm7N3BXgIdGLoOmFBe9LTRn6NLbH1Bs1Hbte61k6uGokxw==",
                            UserName = "Delbert.Bauch"
                        },
                        new
                        {
                            CustomerId = 51,
                            FirstName = "Christopher",
                            IsAdmin = false,
                            LastName = "Veum",
                            PasswordHash = "uQEzDPsvySMbLkug6ndBdApWQjuqnvq5:0eb1JQ7bnjwBFEsLgPvrkx7TZwV0P9HWx62Yw/QyNnPnP1Y0S9BnyE6AJUMITB6XeBJxP9WsKWHksf/nz+yu8Q==",
                            UserName = "Christopher_Veum60"
                        },
                        new
                        {
                            CustomerId = 52,
                            FirstName = "Annette",
                            IsAdmin = false,
                            LastName = "Simonis",
                            PasswordHash = "tGEyixtVucNu5qd29mH36p2ev9Rz8hOk:nHEOaONYAK16Nu8+3A0gueGNZsk52WgrKYSG095xHV9Gc4sLghTIWxibef5LYuT5aB3w0CFRDHoHi+q0Rszv5g==",
                            UserName = "Annette0"
                        },
                        new
                        {
                            CustomerId = 53,
                            FirstName = "Guy",
                            IsAdmin = false,
                            LastName = "Rodriguez",
                            PasswordHash = "yF25lr6zQttUoWJbsDfKwXg4IB7Ul3Oz:oNFlkspe+MAKym2wilkjFA3ywrUCUvYXLAyO4qKUUHSZYLDk5AT3dKiomYIkH/bh2bY+EpyiC+mvAot47rpJgg==",
                            UserName = "Guy.Rodriguez54"
                        },
                        new
                        {
                            CustomerId = 54,
                            FirstName = "Jenny",
                            IsAdmin = false,
                            LastName = "Marvin",
                            PasswordHash = "94zKV+Kp6cz5FlpBn9pbfO8dekjfcWaT:G7vPOQPol5YD+k3ajsr0wmInhHvfWaEEKJN3wc+Dv75LBXg6JNcckDBj8irB+QqkGDzXkN7ADqMfMkawPYLnvw==",
                            UserName = "Jenny8"
                        },
                        new
                        {
                            CustomerId = 55,
                            FirstName = "Daisy",
                            IsAdmin = false,
                            LastName = "Swaniawski",
                            PasswordHash = "d44XHjQeIQ1yZ4Lyyxhfhg+MFVPC+E9R:9H9oS/+17+UqFG8Q1mFPUDqnGfVf03lkogC/PhxVDG2XEz2YyuGP3kpSwdN30UX/bndmctvrXo85KlcJN4TLoQ==",
                            UserName = "Daisy.Swaniawski13"
                        },
                        new
                        {
                            CustomerId = 56,
                            FirstName = "Mercedes",
                            IsAdmin = false,
                            LastName = "Gibson",
                            PasswordHash = "F1OinBFfo9Nj8/GKlXCBf7CUzwsxR+OA:Wfy4q8qrU2RFzrle0nqYrMNhrNMtZmCEDAggCJjKxvkBidtgKVDnlqVY7VWPvunvHqPD7NJg42b+VQ9gnp+ZNg==",
                            UserName = "Mercedes_Gibson"
                        },
                        new
                        {
                            CustomerId = 57,
                            FirstName = "Lucy",
                            IsAdmin = false,
                            LastName = "Larkin",
                            PasswordHash = "y9Jw/dzQtxwV0h6MfWWeXEQ8FWtviS5I:4XLg9HFmLmPLdZoHWsv5i9ya5WW/g0egRJt9/94p4VNuNvyhZ1yQ+y1fwtZqNUUu1zu+8UyRThe6aBUGtRm/jA==",
                            UserName = "Lucy47"
                        },
                        new
                        {
                            CustomerId = 58,
                            FirstName = "Jana",
                            IsAdmin = false,
                            LastName = "Kozey",
                            PasswordHash = "FfGSDREAiAd2GODyx/AiDUa527FryxjL:RnITZpzGFhnDoAyA+N9EJV4Yc21z9V4TTcQaMRo3vZuAAmMuhzIaS0TaUQlkq+51OXl+luj8wd5Ym63MlC1eDA==",
                            UserName = "Jana36"
                        },
                        new
                        {
                            CustomerId = 59,
                            FirstName = "Victoria",
                            IsAdmin = false,
                            LastName = "Yost",
                            PasswordHash = "ezzXe852RgoXNnnjMfb80o4xA6ET2sEC:q+DAedyyxab7fTwgYiIlE5uEDtEpmyG1e1kFIkDMQ3Ef30yjXRChuBYId30CqfUmYHEHfKUq9H2b/bnTSY8DxQ==",
                            UserName = "Victoria32"
                        },
                        new
                        {
                            CustomerId = 60,
                            FirstName = "Rachel",
                            IsAdmin = false,
                            LastName = "Douglas",
                            PasswordHash = "0f1bwllafdOYmn24j4G79CofZdMEqeBs:2WMRMpTipo+V+YiCnF+rL5s1rQXvNN6s7yijG1AW+CCtu25TSqMQR8iGApDDa9nYSOndq6HEAwGPiqCcJrAYHg==",
                            UserName = "Rachel_Douglas"
                        },
                        new
                        {
                            CustomerId = 61,
                            FirstName = "Boyd",
                            IsAdmin = false,
                            LastName = "Labadie",
                            PasswordHash = "cSzPeIuODRTD/cNYqEo9MiFD/DyeZHCL:7DUxy9Rzyep1sySybvWDc3owqKRZZ2kmqR7yI2t+b1Oq0XGYVM0db0CpAXN5ISSZ1XmKmvwxt2T8T+0Ja96tqg==",
                            UserName = "Boyd.Labadie20"
                        },
                        new
                        {
                            CustomerId = 62,
                            FirstName = "Tracy",
                            IsAdmin = false,
                            LastName = "Deckow",
                            PasswordHash = "0gJAT5DKwc3kBpyjPOxl3Dz51l/rjdni:cqJ7Tstp7rve1Oh40xCCo8MEkcsBLL1Z5PGKrzhU59yOD4S+0wEqQSSGQxCdyK4jJuPkqKRglB/cqk5DrN81kg==",
                            UserName = "Tracy96"
                        },
                        new
                        {
                            CustomerId = 63,
                            FirstName = "Rosie",
                            IsAdmin = false,
                            LastName = "Reichert",
                            PasswordHash = "lLqJRQhndjNEN7RWMHl8cKmwm66D/eMB:cWu2I61p5yWW8mCK41yW33H9sJ3QVARv8eS0ag8EpjQHcs9zuFwJkFdj9O7vUM8/0pgL7j6P/Sc8F3/tX1a4IA==",
                            UserName = "Rosie.Reichert"
                        },
                        new
                        {
                            CustomerId = 64,
                            FirstName = "Margaret",
                            IsAdmin = false,
                            LastName = "Torp",
                            PasswordHash = "fYY88EkvgbM47UdJntTdatnNvALDE2MI:1NCpwJNHXoK13XCRG5alXjlIjY0OkgBNvRBcKhZ9UA/LMOEoWeSBELhUjjMSVY55/s3UMDyJmrd/JUwEkMxzEQ==",
                            UserName = "Margaret.Torp"
                        },
                        new
                        {
                            CustomerId = 65,
                            FirstName = "Lynn",
                            IsAdmin = false,
                            LastName = "Lowe",
                            PasswordHash = "hMgZnWuDCxeKt/HgpNEs2CBAKFFGbLf3:tBuWofSqRQtVW8PVz6Y7Rwv6auddIEne57jMrN256iXbiErNDvcdEHLiBBkO5ymKzuSTh0q7uQatz3poJYHJHA==",
                            UserName = "Lynn_Lowe"
                        },
                        new
                        {
                            CustomerId = 66,
                            FirstName = "Carlos",
                            IsAdmin = false,
                            LastName = "Brown",
                            PasswordHash = "4WFkt6j2swmGU5ETlLbBxF/zdht7YesV:S6LUf0m/t8fBrG2bhlAEBD1DopvwZw7fX6ge6Z/OrPfzkXiJDVGqShdOywZ5NWQIxKholzWrSdGcOoA2C1cukg==",
                            UserName = "Carlos_Brown72"
                        },
                        new
                        {
                            CustomerId = 67,
                            FirstName = "Julian",
                            IsAdmin = false,
                            LastName = "Grant",
                            PasswordHash = "PrrOwR9APSs48vzvjWoAE1Ss2WHl/md/:4poHGbTsMnjum8+9C3YR0nAluz0Zy2p9CFZadg4v6Ilh9Rr/QFtAy9M7sg1lpIStJJhRxTX1+qzyzHl0ddpp4g==",
                            UserName = "Julian_Grant"
                        },
                        new
                        {
                            CustomerId = 68,
                            FirstName = "Juana",
                            IsAdmin = false,
                            LastName = "Ryan",
                            PasswordHash = "ttzTCNuN6GYJzuLcURICYl8lItEmEjkp:whOzdPGDvA0wR3zqV/fzcV7aFMAKqKDKfK0o4AseFf5h28U6J/Gvjbgy7POtgvAPUhbCPHm4lJUwvJkaCCrfsg==",
                            UserName = "Juana.Ryan84"
                        },
                        new
                        {
                            CustomerId = 69,
                            FirstName = "Cody",
                            IsAdmin = false,
                            LastName = "Kunde",
                            PasswordHash = "insHvi0GC52hVtIQkWHLyHyDAobvUh5L:HqdY59gp6mzDGyNd65HSOz3NKtqdCCjEQysScTZzlduEx7xhMNrrRNn0Qx1vfz29j0e22u83efBbzKcH0+oyJQ==",
                            UserName = "Cody43"
                        },
                        new
                        {
                            CustomerId = 70,
                            FirstName = "Stanley",
                            IsAdmin = false,
                            LastName = "Gaylord",
                            PasswordHash = "jyCA90P+9vKhVUb1zmz0D9vxkAMO0kcC:ovsDNpcBRXo1xoCIzlhfQYLJkdvw8FpVTo5lxEpZkm5aH463TzI2Yuj2UrEYtcrIXBMya5+Wt0w7Iu2AsvmW2A==",
                            UserName = "Stanley64"
                        },
                        new
                        {
                            CustomerId = 71,
                            FirstName = "Dallas",
                            IsAdmin = false,
                            LastName = "Reynolds",
                            PasswordHash = "IH2bmL1szhZD5SiXnmiAKnBTWOnJFwHe:L6RojA8IUJZo+G+u9R9dtScmEQ2QOdPmL8lPjE0vnJe/35v3V77TgQmMuNbh44iGZF7zTRW/xg+fKp2xMNXE9Q==",
                            UserName = "Dallas.Reynolds17"
                        },
                        new
                        {
                            CustomerId = 72,
                            FirstName = "Bernard",
                            IsAdmin = false,
                            LastName = "Buckridge",
                            PasswordHash = "18Eg/dresTHAQArnGEgNYwtnEjYbhGgm:LNI1P8cmwY4VICIc/Q+nVvNTQHP69aIA0gdrxUogIlgZo8Habg7gtdvBoxAhbDk+rYaNg4M3SiGliUdx2p7H8g==",
                            UserName = "Bernard_Buckridge80"
                        },
                        new
                        {
                            CustomerId = 73,
                            FirstName = "Lori",
                            IsAdmin = false,
                            LastName = "Ruecker",
                            PasswordHash = "zG81ILjsAhzJWTedkzBah6q5WAi47dQv:wpiizVKwCBQcPv+7d+J3uVJy+FY98ZsPV5EiNUHy2QaXp1+PO8q89NYrh5M391/eQQOTxSNUMAOHNJJQPlVpEQ==",
                            UserName = "Lori.Ruecker"
                        },
                        new
                        {
                            CustomerId = 74,
                            FirstName = "Martin",
                            IsAdmin = false,
                            LastName = "Rippin",
                            PasswordHash = "JFSSLMiuDjqQiisbSBCf4vCKk1Mh3o66:lmXw2ISqE4fBOMtmQjgVwQ1KAAudAeoiTH7HXjnMut7hdXhj4bAGOF5mXaOq1OkBk/CjqkeZ9Bk7hFhHE2iwZQ==",
                            UserName = "Martin_Rippin37"
                        },
                        new
                        {
                            CustomerId = 75,
                            FirstName = "Nicolas",
                            IsAdmin = false,
                            LastName = "Fritsch",
                            PasswordHash = "vMdFDRH7aVJNbbEGNs7IJAvPKkmtSZDg:nf5nMcnVJ8po8FlBZfVbz11KwCEE8EKerlv4pbTPT63Xbafql/43p1qcuOokArnR8HChZ9GeL8qyeV/HNb5INg==",
                            UserName = "Nicolas70"
                        },
                        new
                        {
                            CustomerId = 76,
                            FirstName = "Ervin",
                            IsAdmin = false,
                            LastName = "Weimann",
                            PasswordHash = "+Vh/K4FX9Lln87IByYWnYoWABke/Cn84:aLPqnqcz0v5lFG7mU72DLYEXSz8f4dJJzd8DWL3oOMTGynLRhozJbOBU/oZ0rwPloqqdLu61sCpZfhm1zCieVQ==",
                            UserName = "Ervin31"
                        },
                        new
                        {
                            CustomerId = 77,
                            FirstName = "Kerry",
                            IsAdmin = false,
                            LastName = "Hudson",
                            PasswordHash = "dChNfAzjIK/H3rgfZy2fwMQ6Z9VVrowh:u3o+uHj84sl/h6zD9Tmg6CiLeU608u/lzSMybRPJx8R/rupQP0Nj9EpuiA4VKXg1Rk1RotRPWldAVUoQV9hHzw==",
                            UserName = "Kerry_Hudson94"
                        },
                        new
                        {
                            CustomerId = 78,
                            FirstName = "Frank",
                            IsAdmin = false,
                            LastName = "Ratke",
                            PasswordHash = "tViEFugbeNn1ud3EaLCVZ/mQ9HnrYb37:m3bVHj7C7DuvhFDd7UR2yoeRBbj7r34LG09SEg6NubFv2eGJMHFKv/9/8zSMQYFzY6kF5RTqdeWUehCZEy4/EQ==",
                            UserName = "Frank_Ratke64"
                        },
                        new
                        {
                            CustomerId = 79,
                            FirstName = "Lillian",
                            IsAdmin = false,
                            LastName = "Rodriguez",
                            PasswordHash = "N4IGFyIfgCzDhM7BOczisJM3v7A3U33u:G/1gJB7pz1OS7LrEaQNtxmlCMk2FQKl+IVSGd2SHXXLNpoC07nMwEBrsgd788lXGC1OnlPANW4LFtULHiUqZSA==",
                            UserName = "Lillian_Rodriguez"
                        },
                        new
                        {
                            CustomerId = 80,
                            FirstName = "Beverly",
                            IsAdmin = false,
                            LastName = "Thompson",
                            PasswordHash = "ShhfkqgSRsaVH+dLwhWyt/hLjMFaC/0V:ipTVdTR5/HeOrJFaP8AWG0D/mzkSQES9TNR+kFk3nVjQjhJI6b2y2EPB01PKHhaBmQ/7GxnbTJKil0g567K37g==",
                            UserName = "Beverly8"
                        },
                        new
                        {
                            CustomerId = 81,
                            FirstName = "Keith",
                            IsAdmin = false,
                            LastName = "Murray",
                            PasswordHash = "xn7XSnKbw8l3B/ytfMAgRXc85qSRlMvj:k8aXwKlj4a+1K2hwzHuqgE6G1st7J5w8xP0+Fbre9XMDkJ5IQ3z/3+aNSAkK3PD5Cj8wfF4tOYqsqumn8eytfg==",
                            UserName = "Keith_Murray"
                        },
                        new
                        {
                            CustomerId = 82,
                            FirstName = "Kara",
                            IsAdmin = false,
                            LastName = "Block",
                            PasswordHash = "6Fyfe/ZsiGL309upBSdy/6hro5F6VJwt:M28r4s5ohAfHIyOVswtVK2rAReaqtvdDo4puxlzUZxAp4FszG58Q0Znu0GCcOsA8vDhk7NQTcbA0BkT63+FZrA==",
                            UserName = "Kara95"
                        },
                        new
                        {
                            CustomerId = 83,
                            FirstName = "Kimberly",
                            IsAdmin = false,
                            LastName = "Breitenberg",
                            PasswordHash = "oM7MNwlDih4b3d9JcBEN0X8Jxchxt5BP:9kXxa5oakQZXPdcQ3RG6cIGO7nm6DgHisnO0Jzw/9zhzgEbNnSUbOi6zr/a3Ex3ZVS1vmACJLuYXn7FKtwFfMg==",
                            UserName = "Kimberly79"
                        },
                        new
                        {
                            CustomerId = 84,
                            FirstName = "Maurice",
                            IsAdmin = false,
                            LastName = "Kutch",
                            PasswordHash = "qQ5MrB4tql1jj6v06loou470Jwd2qaXS:TcTLrrxzcA+YvrO2X4rI5lJ0AYLldgaKz6r9qjCsuxQm3lhiRtyJGFtUZobBSo148T0XOcwLzLVALaicvtsFLQ==",
                            UserName = "Maurice_Kutch2"
                        },
                        new
                        {
                            CustomerId = 85,
                            FirstName = "Damon",
                            IsAdmin = false,
                            LastName = "Kerluke",
                            PasswordHash = "GqVvBSp9w+pORchipCyu3G11FK37GK3X:FVf063rW1ilr+GrQnhrFR/vlZrgFZJEemA8SyOPcmjlQZ+WHXZGO0J/mTNocGOBL8P7FLCakPkr3VFrNriWtNA==",
                            UserName = "Damon.Kerluke"
                        },
                        new
                        {
                            CustomerId = 86,
                            FirstName = "Wayne",
                            IsAdmin = false,
                            LastName = "Beier",
                            PasswordHash = "2e2s6aATWxrBWQVHls4LIXxdOGJ1mcpE:wCN33WzMubAk0IAQZJ1j3jdhi5VskqwFbhra26FfrdCLAvf4F06yGNVjuYw5JYfgivnwpbzHJ9f90i6y6MUcTw==",
                            UserName = "Wayne32"
                        },
                        new
                        {
                            CustomerId = 87,
                            FirstName = "Vera",
                            IsAdmin = false,
                            LastName = "Nolan",
                            PasswordHash = "7rW9U+rotidplwPFugxv1z6M61ZSkY4x:Nip1BGWXLK2YsmAea4DNdlEoSV3BizEwysN/xyLB40pyJaOf5qfVq/6teODmMOLcf4wP6iVDe73rp6/9NFNxng==",
                            UserName = "Vera35"
                        },
                        new
                        {
                            CustomerId = 88,
                            FirstName = "Sabrina",
                            IsAdmin = false,
                            LastName = "Leuschke",
                            PasswordHash = "6sYUDAdJ8E/XFHPp4wovn5OiW6/rppQC:rwllEkelPjNrl83V3Gw+A5W/nIE/tXL1EFmDSx27bLyD5htf0ktNO+NyFbf1Up0M7EQTli6fboIbRYwL6+3FXg==",
                            UserName = "Sabrina.Leuschke53"
                        },
                        new
                        {
                            CustomerId = 89,
                            FirstName = "Michael",
                            IsAdmin = false,
                            LastName = "Windler",
                            PasswordHash = "n7UPsnokw9SA5ScY5j+8cZ/bqRRuUamz:E+FZR4+nmPDE+MOQfqhz4JiGGZJlustJ1WFFKOnd/xvrjH4rPY1oDmKvgd7xDqWpSuRrMcJqCaU/Nm3WjbSZnw==",
                            UserName = "Michael.Windler66"
                        },
                        new
                        {
                            CustomerId = 90,
                            FirstName = "Dan",
                            IsAdmin = false,
                            LastName = "Lemke",
                            PasswordHash = "dahYPsrGe5syE/JLFjM4rCP9Wg1gvrkA:C8OrGr6PKwTH9HoKaVia2a292DhgqTurl1hBDAKJJNbRcrmyt34fGlEd009FE7zXUL3IfbpScohNxNgjQQ0pBA==",
                            UserName = "Dan_Lemke92"
                        },
                        new
                        {
                            CustomerId = 91,
                            FirstName = "Faith",
                            IsAdmin = false,
                            LastName = "Heathcote",
                            PasswordHash = "4bFug6fsR5iT4aFMz9ywHF7+4sCxJyWd:GQmUdWEDR3tLbsdHa/N6NKheEZaCD9GH7a+eCATcupwVoeq/oPsOKevSzsD9ZeTzS137g/22FesVaZH9dCcnnw==",
                            UserName = "Faith_Heathcote20"
                        },
                        new
                        {
                            CustomerId = 92,
                            FirstName = "Terrence",
                            IsAdmin = false,
                            LastName = "Effertz",
                            PasswordHash = "jGSRKMarmF4Lf11fcRG5nFPcBzCmoXtQ:tnXBWu9rjnj5tBsr3Qi/smsj/3rZeqQjFcbGqhhxMJXmhfrE5E8ff7+y7ccOikCDDz3QYQGeIsJA7FMtfm6b9Q==",
                            UserName = "Terrence35"
                        },
                        new
                        {
                            CustomerId = 93,
                            FirstName = "Ben",
                            IsAdmin = false,
                            LastName = "O'Conner",
                            PasswordHash = "j6rFAEw7UewEOoT6P3yaSQrbq7MrMnEI:RhXoFx43Y88aPDjJXloPt3Am/3CY6YzEAAx7A7/nforaqzl/CCL4l9Tzv3yhx4tIwSjF2U4+MLxUM9lUO8o5Pw==",
                            UserName = "Ben_OConner"
                        },
                        new
                        {
                            CustomerId = 94,
                            FirstName = "Cristina",
                            IsAdmin = false,
                            LastName = "Frami",
                            PasswordHash = "4KHO+il26L+6piVN3wZ1lFDUzWvoSFNG:ivw/MYOt3LmKebPOhUW4oaYH3AXDi5anz6lXz62TyVKsxFekpvRMjr9UzgpXHaJt77xAyzvTZK8vr8gC81ps4A==",
                            UserName = "Cristina.Frami67"
                        },
                        new
                        {
                            CustomerId = 95,
                            FirstName = "Melody",
                            IsAdmin = false,
                            LastName = "Will",
                            PasswordHash = "+6VhAmQxCqCtpqosfC9Q20yxiNAO8wK8:3M4pdpKrz5aFZ2jjfPCYtqrYh43/NEUZDWy/wPvqipzpzhwebA+IHCfDCdvAfO+ZJlq5/zihVfXFSWZRYkzIOQ==",
                            UserName = "Melody8"
                        },
                        new
                        {
                            CustomerId = 96,
                            FirstName = "Angie",
                            IsAdmin = false,
                            LastName = "Hudson",
                            PasswordHash = "UYoIqZoyur5RI/lmFvYrmT87JzuKTYC+:kXiooo/SowuJnBXqBKED9cpzdVxVZA8P3YX+bsB4al7RG9cL14G8PTjIznCK6Mvw7XzRkuNtKULNqIHfPE3d9g==",
                            UserName = "Angie_Hudson"
                        },
                        new
                        {
                            CustomerId = 97,
                            FirstName = "Carlton",
                            IsAdmin = false,
                            LastName = "Ledner",
                            PasswordHash = "oqLiwreqKg4mizkyDdXwMJoyOk9Wn4vB:3lTypBA4jaAGziFrEfm5t3dp0b1lSDUSdNDGR6/qBoJhIN6RKsvS1Nn4BAvDadp4OOE6UQdiPF+IlA893RBDwA==",
                            UserName = "Carlton75"
                        },
                        new
                        {
                            CustomerId = 98,
                            FirstName = "Harold",
                            IsAdmin = false,
                            LastName = "Hettinger",
                            PasswordHash = "Im/9GSyDi/501Ho7s6IYNafLKG2cu71r:9h/8CeV8RCTGxNwPbJnsvPYUdyBoqKjaaZc/hRx8cPg2hUqoYDzWW34i7N38e93oApvFW3AmvmDsx+BrZPSWjw==",
                            UserName = "Harold44"
                        },
                        new
                        {
                            CustomerId = 99,
                            FirstName = "Tonya",
                            IsAdmin = false,
                            LastName = "Hagenes",
                            PasswordHash = "bWEVl988TnOGPLS81fmnAncwf3vlkhAg:6zP3juV434PXo1rmUPu4Rz04rC4WT0h+PQWdniOuIVgo//xaL6icEEwHyPRpthBRoLH9eVYW68gXDu901JgHxA==",
                            UserName = "Tonya_Hagenes30"
                        },
                        new
                        {
                            CustomerId = 100,
                            FirstName = "Kate",
                            IsAdmin = false,
                            LastName = "McDermott",
                            PasswordHash = "16Mfy7/9HW/xxHt79gZqgo1SI66AAyFr:UzlxLNIbiIqKNdgs/Mn5tOY96ggaxAODMylAKqDxtd+YrqBoOTTPjeCq7ooeX0GQaDjAypkA4oJNUO1cuMJWYQ==",
                            UserName = "Kate88"
                        },
                        new
                        {
                            CustomerId = 101,
                            FirstName = "Mario",
                            IsAdmin = false,
                            LastName = "Bogan",
                            PasswordHash = "YpDFknDT6wBrjR/l/RQepypK0/jgzixZ:f46WKh+EIe+wjXEXqBXdVcb95KFsECM3vB/dZ1tpEXeflGvPIll6lppcz8idmefd5fmGcsUl1YVpUXfdxRkEOA==",
                            UserName = "Mario.Bogan1"
                        });
                });

            modelBuilder.Entity("MooveTeqBooking.Data.Booking", b =>
                {
                    b.HasOne("MooveTeqBooking.Data.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
