// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScooTeqBooking.Data;

namespace ScooTeqBooking.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15");

            modelBuilder.Entity("MooveTeqBooking.Data.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalTripCost")
                        .HasColumnType("REAL");

                    b.Property<int?>("TripDiscountPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TripDistance")
                        .HasColumnType("REAL");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MooveTeqBooking.Data.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            FirstName = "Demo",
                            IsAdmin = true,
                            LastName = "Admin",
                            PasswordHash = "qQnYyvK/vjABTZvbbL7ZeSWpaRx6OoDY:nZ1pFR3XGgp3+NyrbW7Xrt56kWiZ91F2fSIFHt1yQwo0E9BuSa4vuLvbQuBJk7WFA2ILpUaxoARMPoh8uu2EHw==",
                            UserName = "admin"
                        },
                        new
                        {
                            CustomerId = 2,
                            FirstName = "Douglas",
                            IsAdmin = false,
                            LastName = "Shanahan",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Douglas72"
                        },
                        new
                        {
                            CustomerId = 3,
                            FirstName = "Lydia",
                            IsAdmin = false,
                            LastName = "Stroman",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Lydia51"
                        },
                        new
                        {
                            CustomerId = 4,
                            FirstName = "Nina",
                            IsAdmin = false,
                            LastName = "Russel",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Nina.Russel"
                        },
                        new
                        {
                            CustomerId = 5,
                            FirstName = "Salvador",
                            IsAdmin = false,
                            LastName = "Fritsch",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Salvador_Fritsch46"
                        },
                        new
                        {
                            CustomerId = 6,
                            FirstName = "Benny",
                            IsAdmin = false,
                            LastName = "Gulgowski",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Benny.Gulgowski63"
                        },
                        new
                        {
                            CustomerId = 7,
                            FirstName = "Kristin",
                            IsAdmin = false,
                            LastName = "Trantow",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Kristin.Trantow"
                        },
                        new
                        {
                            CustomerId = 8,
                            FirstName = "Dianne",
                            IsAdmin = false,
                            LastName = "Powlowski",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Dianne.Powlowski57"
                        },
                        new
                        {
                            CustomerId = 9,
                            FirstName = "Cassandra",
                            IsAdmin = false,
                            LastName = "Goldner",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Cassandra_Goldner"
                        },
                        new
                        {
                            CustomerId = 10,
                            FirstName = "Arturo",
                            IsAdmin = false,
                            LastName = "Steuber",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Arturo71"
                        },
                        new
                        {
                            CustomerId = 11,
                            FirstName = "Abel",
                            IsAdmin = false,
                            LastName = "Swift",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Abel.Swift54"
                        },
                        new
                        {
                            CustomerId = 12,
                            FirstName = "Daisy",
                            IsAdmin = false,
                            LastName = "Brakus",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Daisy25"
                        },
                        new
                        {
                            CustomerId = 13,
                            FirstName = "Sheryl",
                            IsAdmin = false,
                            LastName = "Dicki",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Sheryl_Dicki13"
                        },
                        new
                        {
                            CustomerId = 14,
                            FirstName = "Jenna",
                            IsAdmin = false,
                            LastName = "Treutel",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Jenna63"
                        },
                        new
                        {
                            CustomerId = 15,
                            FirstName = "Guadalupe",
                            IsAdmin = false,
                            LastName = "Murazik",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Guadalupe.Murazik53"
                        },
                        new
                        {
                            CustomerId = 16,
                            FirstName = "Josefina",
                            IsAdmin = false,
                            LastName = "Gorczany",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Josefina0"
                        },
                        new
                        {
                            CustomerId = 17,
                            FirstName = "Ana",
                            IsAdmin = false,
                            LastName = "Spinka",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Ana_Spinka82"
                        },
                        new
                        {
                            CustomerId = 18,
                            FirstName = "Kristine",
                            IsAdmin = false,
                            LastName = "Buckridge",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Kristine_Buckridge81"
                        },
                        new
                        {
                            CustomerId = 19,
                            FirstName = "Irvin",
                            IsAdmin = false,
                            LastName = "Douglas",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Irvin_Douglas"
                        },
                        new
                        {
                            CustomerId = 20,
                            FirstName = "Velma",
                            IsAdmin = false,
                            LastName = "McClure",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Velma20"
                        },
                        new
                        {
                            CustomerId = 21,
                            FirstName = "Karla",
                            IsAdmin = false,
                            LastName = "McGlynn",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Karla37"
                        },
                        new
                        {
                            CustomerId = 22,
                            FirstName = "Darnell",
                            IsAdmin = false,
                            LastName = "Moen",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Darnell_Moen47"
                        },
                        new
                        {
                            CustomerId = 23,
                            FirstName = "Joanne",
                            IsAdmin = false,
                            LastName = "Schamberger",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Joanne98"
                        },
                        new
                        {
                            CustomerId = 24,
                            FirstName = "Noah",
                            IsAdmin = false,
                            LastName = "Labadie",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Noah_Labadie20"
                        },
                        new
                        {
                            CustomerId = 25,
                            FirstName = "Tonya",
                            IsAdmin = false,
                            LastName = "Kunze",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Tonya.Kunze32"
                        },
                        new
                        {
                            CustomerId = 26,
                            FirstName = "Louise",
                            IsAdmin = false,
                            LastName = "Gorczany",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Louise96"
                        },
                        new
                        {
                            CustomerId = 27,
                            FirstName = "Betty",
                            IsAdmin = false,
                            LastName = "Reichert",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Betty_Reichert87"
                        },
                        new
                        {
                            CustomerId = 28,
                            FirstName = "Lora",
                            IsAdmin = false,
                            LastName = "Witting",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Lora_Witting"
                        },
                        new
                        {
                            CustomerId = 29,
                            FirstName = "Nadine",
                            IsAdmin = false,
                            LastName = "Cole",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Nadine34"
                        },
                        new
                        {
                            CustomerId = 30,
                            FirstName = "Angelica",
                            IsAdmin = false,
                            LastName = "Robel",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Angelica_Robel"
                        },
                        new
                        {
                            CustomerId = 31,
                            FirstName = "Fredrick",
                            IsAdmin = false,
                            LastName = "Quitzon",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Fredrick94"
                        },
                        new
                        {
                            CustomerId = 32,
                            FirstName = "Margarita",
                            IsAdmin = false,
                            LastName = "Rodriguez",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Margarita.Rodriguez"
                        },
                        new
                        {
                            CustomerId = 33,
                            FirstName = "Timmy",
                            IsAdmin = false,
                            LastName = "Glover",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Timmy72"
                        },
                        new
                        {
                            CustomerId = 34,
                            FirstName = "Amy",
                            IsAdmin = false,
                            LastName = "Kessler",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Amy.Kessler19"
                        },
                        new
                        {
                            CustomerId = 35,
                            FirstName = "Emma",
                            IsAdmin = false,
                            LastName = "Dicki",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Emma_Dicki"
                        },
                        new
                        {
                            CustomerId = 36,
                            FirstName = "Mike",
                            IsAdmin = false,
                            LastName = "Hamill",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Mike94"
                        },
                        new
                        {
                            CustomerId = 37,
                            FirstName = "Mike",
                            IsAdmin = false,
                            LastName = "Reilly",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Mike.Reilly2"
                        },
                        new
                        {
                            CustomerId = 38,
                            FirstName = "Pedro",
                            IsAdmin = false,
                            LastName = "Collier",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Pedro90"
                        },
                        new
                        {
                            CustomerId = 39,
                            FirstName = "Silvia",
                            IsAdmin = false,
                            LastName = "Larson",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Silvia_Larson34"
                        },
                        new
                        {
                            CustomerId = 40,
                            FirstName = "Joseph",
                            IsAdmin = false,
                            LastName = "Runolfsson",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Joseph_Runolfsson25"
                        },
                        new
                        {
                            CustomerId = 41,
                            FirstName = "Fredrick",
                            IsAdmin = false,
                            LastName = "Ratke",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Fredrick.Ratke"
                        },
                        new
                        {
                            CustomerId = 42,
                            FirstName = "Edith",
                            IsAdmin = false,
                            LastName = "McDermott",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Edith.McDermott"
                        },
                        new
                        {
                            CustomerId = 43,
                            FirstName = "Karl",
                            IsAdmin = false,
                            LastName = "Ward",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Karl.Ward"
                        },
                        new
                        {
                            CustomerId = 44,
                            FirstName = "Karen",
                            IsAdmin = false,
                            LastName = "Larkin",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Karen.Larkin4"
                        },
                        new
                        {
                            CustomerId = 45,
                            FirstName = "Alicia",
                            IsAdmin = false,
                            LastName = "Runolfsdottir",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Alicia.Runolfsdottir"
                        },
                        new
                        {
                            CustomerId = 46,
                            FirstName = "Angie",
                            IsAdmin = false,
                            LastName = "Satterfield",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Angie.Satterfield"
                        },
                        new
                        {
                            CustomerId = 47,
                            FirstName = "Sheila",
                            IsAdmin = false,
                            LastName = "Wintheiser",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Sheila_Wintheiser89"
                        },
                        new
                        {
                            CustomerId = 48,
                            FirstName = "Toni",
                            IsAdmin = false,
                            LastName = "Armstrong",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Toni.Armstrong"
                        },
                        new
                        {
                            CustomerId = 49,
                            FirstName = "Sheri",
                            IsAdmin = false,
                            LastName = "Lind",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Sheri.Lind"
                        },
                        new
                        {
                            CustomerId = 50,
                            FirstName = "Robin",
                            IsAdmin = false,
                            LastName = "Johnson",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Robin_Johnson"
                        },
                        new
                        {
                            CustomerId = 51,
                            FirstName = "Brenda",
                            IsAdmin = false,
                            LastName = "Cormier",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Brenda_Cormier8"
                        },
                        new
                        {
                            CustomerId = 52,
                            FirstName = "Edith",
                            IsAdmin = false,
                            LastName = "Watsica",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Edith_Watsica"
                        },
                        new
                        {
                            CustomerId = 53,
                            FirstName = "Jill",
                            IsAdmin = false,
                            LastName = "Huels",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Jill.Huels44"
                        },
                        new
                        {
                            CustomerId = 54,
                            FirstName = "Jodi",
                            IsAdmin = false,
                            LastName = "Russel",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Jodi21"
                        },
                        new
                        {
                            CustomerId = 55,
                            FirstName = "Carlton",
                            IsAdmin = false,
                            LastName = "Paucek",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Carlton.Paucek"
                        },
                        new
                        {
                            CustomerId = 56,
                            FirstName = "Doyle",
                            IsAdmin = false,
                            LastName = "Bode",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Doyle_Bode"
                        },
                        new
                        {
                            CustomerId = 57,
                            FirstName = "Lori",
                            IsAdmin = false,
                            LastName = "Graham",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Lori.Graham"
                        },
                        new
                        {
                            CustomerId = 58,
                            FirstName = "Kirk",
                            IsAdmin = false,
                            LastName = "Hand",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Kirk13"
                        },
                        new
                        {
                            CustomerId = 59,
                            FirstName = "Constance",
                            IsAdmin = false,
                            LastName = "Schimmel",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Constance72"
                        },
                        new
                        {
                            CustomerId = 60,
                            FirstName = "Sophie",
                            IsAdmin = false,
                            LastName = "Murray",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Sophie_Murray"
                        },
                        new
                        {
                            CustomerId = 61,
                            FirstName = "Robin",
                            IsAdmin = false,
                            LastName = "Blanda",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Robin_Blanda"
                        },
                        new
                        {
                            CustomerId = 62,
                            FirstName = "Kelly",
                            IsAdmin = false,
                            LastName = "Quigley",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Kelly_Quigley"
                        },
                        new
                        {
                            CustomerId = 63,
                            FirstName = "Hubert",
                            IsAdmin = false,
                            LastName = "Spinka",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Hubert_Spinka99"
                        },
                        new
                        {
                            CustomerId = 64,
                            FirstName = "Ollie",
                            IsAdmin = false,
                            LastName = "Abshire",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Ollie60"
                        },
                        new
                        {
                            CustomerId = 65,
                            FirstName = "Arthur",
                            IsAdmin = false,
                            LastName = "Champlin",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Arthur.Champlin80"
                        },
                        new
                        {
                            CustomerId = 66,
                            FirstName = "Courtney",
                            IsAdmin = false,
                            LastName = "White",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Courtney.White65"
                        },
                        new
                        {
                            CustomerId = 67,
                            FirstName = "Leah",
                            IsAdmin = false,
                            LastName = "Muller",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Leah45"
                        },
                        new
                        {
                            CustomerId = 68,
                            FirstName = "Gerard",
                            IsAdmin = false,
                            LastName = "Boyle",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Gerard_Boyle36"
                        },
                        new
                        {
                            CustomerId = 69,
                            FirstName = "Dawn",
                            IsAdmin = false,
                            LastName = "Spinka",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Dawn_Spinka40"
                        },
                        new
                        {
                            CustomerId = 70,
                            FirstName = "Percy",
                            IsAdmin = false,
                            LastName = "Friesen",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Percy_Friesen20"
                        },
                        new
                        {
                            CustomerId = 71,
                            FirstName = "Karen",
                            IsAdmin = false,
                            LastName = "Schultz",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Karen_Schultz"
                        },
                        new
                        {
                            CustomerId = 72,
                            FirstName = "John",
                            IsAdmin = false,
                            LastName = "Rogahn",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "John12"
                        },
                        new
                        {
                            CustomerId = 73,
                            FirstName = "Jesus",
                            IsAdmin = false,
                            LastName = "Carter",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Jesus52"
                        },
                        new
                        {
                            CustomerId = 74,
                            FirstName = "Gwen",
                            IsAdmin = false,
                            LastName = "Jast",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Gwen_Jast"
                        },
                        new
                        {
                            CustomerId = 75,
                            FirstName = "Sidney",
                            IsAdmin = false,
                            LastName = "Smith",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Sidney0"
                        },
                        new
                        {
                            CustomerId = 76,
                            FirstName = "Donald",
                            IsAdmin = false,
                            LastName = "Legros",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Donald88"
                        },
                        new
                        {
                            CustomerId = 77,
                            FirstName = "Orville",
                            IsAdmin = false,
                            LastName = "Kuhic",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Orville_Kuhic"
                        },
                        new
                        {
                            CustomerId = 78,
                            FirstName = "Anthony",
                            IsAdmin = false,
                            LastName = "Casper",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Anthony98"
                        },
                        new
                        {
                            CustomerId = 79,
                            FirstName = "Marion",
                            IsAdmin = false,
                            LastName = "Kertzmann",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Marion26"
                        },
                        new
                        {
                            CustomerId = 80,
                            FirstName = "Yvonne",
                            IsAdmin = false,
                            LastName = "Watsica",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Yvonne59"
                        },
                        new
                        {
                            CustomerId = 81,
                            FirstName = "Renee",
                            IsAdmin = false,
                            LastName = "Hettinger",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Renee_Hettinger"
                        },
                        new
                        {
                            CustomerId = 82,
                            FirstName = "Irene",
                            IsAdmin = false,
                            LastName = "Pagac",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Irene38"
                        },
                        new
                        {
                            CustomerId = 83,
                            FirstName = "Alberta",
                            IsAdmin = false,
                            LastName = "Wiza",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Alberta.Wiza"
                        },
                        new
                        {
                            CustomerId = 84,
                            FirstName = "Janie",
                            IsAdmin = false,
                            LastName = "Bins",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Janie28"
                        },
                        new
                        {
                            CustomerId = 85,
                            FirstName = "Caleb",
                            IsAdmin = false,
                            LastName = "Altenwerth",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Caleb23"
                        },
                        new
                        {
                            CustomerId = 86,
                            FirstName = "Jeffrey",
                            IsAdmin = false,
                            LastName = "Nicolas",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Jeffrey_Nicolas"
                        },
                        new
                        {
                            CustomerId = 87,
                            FirstName = "Keith",
                            IsAdmin = false,
                            LastName = "Koepp",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Keith21"
                        },
                        new
                        {
                            CustomerId = 88,
                            FirstName = "Rene",
                            IsAdmin = false,
                            LastName = "Kautzer",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Rene_Kautzer"
                        },
                        new
                        {
                            CustomerId = 89,
                            FirstName = "Lowell",
                            IsAdmin = false,
                            LastName = "Zieme",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Lowell21"
                        },
                        new
                        {
                            CustomerId = 90,
                            FirstName = "Inez",
                            IsAdmin = false,
                            LastName = "Gleason",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Inez.Gleason76"
                        },
                        new
                        {
                            CustomerId = 91,
                            FirstName = "Larry",
                            IsAdmin = false,
                            LastName = "Powlowski",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Larry21"
                        },
                        new
                        {
                            CustomerId = 92,
                            FirstName = "Judith",
                            IsAdmin = false,
                            LastName = "Nolan",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Judith.Nolan"
                        },
                        new
                        {
                            CustomerId = 93,
                            FirstName = "Leigh",
                            IsAdmin = false,
                            LastName = "Hickle",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Leigh_Hickle"
                        },
                        new
                        {
                            CustomerId = 94,
                            FirstName = "Donna",
                            IsAdmin = false,
                            LastName = "Wunsch",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Donna92"
                        },
                        new
                        {
                            CustomerId = 95,
                            FirstName = "Byron",
                            IsAdmin = false,
                            LastName = "Hayes",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Byron.Hayes49"
                        },
                        new
                        {
                            CustomerId = 96,
                            FirstName = "Kathy",
                            IsAdmin = false,
                            LastName = "Stracke",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Kathy14"
                        },
                        new
                        {
                            CustomerId = 97,
                            FirstName = "Cheryl",
                            IsAdmin = false,
                            LastName = "Wyman",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Cheryl_Wyman"
                        },
                        new
                        {
                            CustomerId = 98,
                            FirstName = "Rodney",
                            IsAdmin = false,
                            LastName = "Willms",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Rodney_Willms"
                        },
                        new
                        {
                            CustomerId = 99,
                            FirstName = "Bobbie",
                            IsAdmin = false,
                            LastName = "Donnelly",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Bobbie.Donnelly"
                        },
                        new
                        {
                            CustomerId = 100,
                            FirstName = "Teresa",
                            IsAdmin = false,
                            LastName = "Quigley",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Teresa_Quigley"
                        },
                        new
                        {
                            CustomerId = 101,
                            FirstName = "Christian",
                            IsAdmin = false,
                            LastName = "Hessel",
                            PasswordHash = "rsLxtxsnwNez924mH8l6vCqEiPWRfE/2:InCOMn7X76HAYf0Y9YTVAdwkJp8hE1QMUhUW7al+80CWqO0EGjerZWuJ6N4KksSKiouxn3fs/rqY6yEp7s/SPA==",
                            UserName = "Christian29"
                        });
                });

            modelBuilder.Entity("MooveTeqBooking.Data.Booking", b =>
                {
                    b.HasOne("MooveTeqBooking.Data.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
